-- MySQL Script generated by MySQL Workbench
-- 03/06/17 18:57:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jp2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jp2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jp2` DEFAULT CHARACTER SET utf8 ;
USE `jp2` ;

-- -----------------------------------------------------
-- Table `jp2`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jp2`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL COMMENT '',
  `Seleccionada` VARCHAR(1) NULL COMMENT '',
  PRIMARY KEY (`idSucursal`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jp2`.`Solicitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jp2`.`Solicitantes` (
  `idSolicitantes` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NombreSolicitante` VARCHAR(45) NOT NULL COMMENT '',
  `ApellidoSolPa` VARCHAR(30) NOT NULL COMMENT '',
  `ApellidoSolMa` VARCHAR(30) NOT NULL COMMENT '',
  `DomicilioSolicitante` VARCHAR(45) NOT NULL COMMENT '',
  `NumeroSolicitante` VARCHAR(10) NULL COMMENT '',
  `Parentesco` VARCHAR(20) NULL COMMENT '',
  `CiudadSolicitante` VARCHAR(45) NOT NULL COMMENT '',
  `ColoniaSolicitante` VARCHAR(45) NULL COMMENT '',
  `Telefono` VARCHAR(20) NULL COMMENT '',
  `EstadoCivilSolicitante` VARCHAR(45) NULL COMMENT '',
  `Edad` INT NULL COMMENT '',
  PRIMARY KEY (`idSolicitantes`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jp2`.`Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jp2`.`Orden` (
  `Folio` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `FechaOrden` DATE NOT NULL COMMENT '',
  `Sucursal_idSucursal` INT NOT NULL COMMENT '',
  `PersonaAtendio` VARCHAR(45) NOT NULL COMMENT '',
  `LugarDifuncion` VARCHAR(45) NULL COMMENT '',
  `Fecha` DATE NULL COMMENT '',
  `Hora` VARCHAR(10) NULL COMMENT '',
  `Causa` VARCHAR(45) NULL COMMENT '',
  `LugarVelacion` VARCHAR(45) NULL COMMENT '',
  `Panteon` VARCHAR(45) NULL COMMENT '',
  `HoraMisa` VARCHAR(10) NULL COMMENT '',
  `Ubicacion` VARCHAR(45) NULL COMMENT '',
  `FechaMisa` VARCHAR(45) NULL COMMENT '',
  `Iglesia` VARCHAR(45) NULL COMMENT '',
  `Perpetuidad` VARCHAR(3) NULL COMMENT '',
  `Temporal` VARCHAR(20) NULL COMMENT '',
  `HoraSepelio` VARCHAR(20) NULL COMMENT '',
  `Ataud` INT NULL COMMENT '',
  `ModeloAtaud` VARCHAR(45) NULL COMMENT '',
  `Urna` INT NULL COMMENT '',
  `ModeloUrna` VARCHAR(45) NULL COMMENT '',
  `Capillas` INT NULL COMMENT '',
  `Cremacion` INT NULL COMMENT '',
  `Embalsamado` INT NULL COMMENT '',
  `OtrosGastos` INT NULL COMMENT '',
  `Adomicilio` INT NULL COMMENT '',
  `LugarCremacion` VARCHAR(45) NULL COMMENT '',
  `Carroza` INT NULL COMMENT '',
  `Traslado` INT NULL COMMENT '',
  `SubTotal` INT NOT NULL COMMENT '',
  `Impuestos` INT NULL COMMENT '',
  `CertificadoMedico` VARCHAR(45) NULL COMMENT '',
  `Otros` INT NULL COMMENT '',
  `Observaciones` VARCHAR(45) NULL COMMENT '',
  `Total` INT NOT NULL COMMENT '',
  `Solicitantes_idSolicitantes` INT NOT NULL COMMENT '',
  `NombreFinado` VARCHAR(45) NULL COMMENT '',
  `ApellidoFinPa` VARCHAR(30) NULL COMMENT '',
  `ApellidoFinMa` VARCHAR(30) NULL COMMENT '',
  `DomicilioFinado` VARCHAR(45) NULL COMMENT '',
  `NumeroFinado` VARCHAR(10) NULL COMMENT '',
  `Nacionalidad` VARCHAR(45) NULL COMMENT '',
  `CiudadFinado` VARCHAR(45) NULL COMMENT '',
  `ColoniaFinado` VARCHAR(45) NULL COMMENT '',
  `Ocupacion` VARCHAR(30) NULL COMMENT '',
  `FechaNacimiento` DATE NULL COMMENT '',
  `EstadoCivil` VARCHAR(20) NULL COMMENT '',
  `DerechoHabiente` VARCHAR(45) NULL COMMENT '',
  `Edad` INT NULL COMMENT '',
  `Escolaridad` VARCHAR(30) NULL COMMENT '',
  `Sexo` VARCHAR(6) NULL COMMENT '',
  `NombreFinExhumar` VARCHAR(45) NULL COMMENT '',
  `ApellidoPaterno` VARCHAR(30) NULL COMMENT '',
  `ApellidoMaterno` VARCHAR(30) NULL COMMENT '',
  `FechaDifuncionExhumar` DATE NULL COMMENT '',
  `Restante` INT NULL COMMENT '',
  PRIMARY KEY (`Folio`, `Sucursal_idSucursal`, `Solicitantes_idSolicitantes`)  COMMENT '',
  INDEX `fk_OrdenServicio_Sucursal_idx` (`Sucursal_idSucursal` ASC)  COMMENT '',
  INDEX `fk_Orden_Solicitantes1_idx` (`Solicitantes_idSolicitantes` ASC)  COMMENT '',
  CONSTRAINT `fk_OrdenServicio_Sucursal`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `jp2`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_Solicitantes1`
    FOREIGN KEY (`Solicitantes_idSolicitantes`)
    REFERENCES `jp2`.`Solicitantes` (`idSolicitantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jp2`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jp2`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Contraseña` VARCHAR(45) NULL COMMENT '',
  `Privilegios` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idUsuarios`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jp2`.`Apoyo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jp2`.`Apoyo` (
  `idApoyo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha` DATE NULL COMMENT '',
  `Solicitantes_idSolicitantes` INT NOT NULL COMMENT '',
  `Sucursal_idSucursal` INT NOT NULL COMMENT '',
  `PersonaAtendio` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idApoyo`, `Solicitantes_idSolicitantes`, `Sucursal_idSucursal`)  COMMENT '',
  INDEX `fk_Apoyo_Solicitantes1_idx` (`Solicitantes_idSolicitantes` ASC)  COMMENT '',
  INDEX `fk_Apoyo_Sucursal1_idx` (`Sucursal_idSucursal` ASC)  COMMENT '',
  CONSTRAINT `fk_Apoyo_Solicitantes1`
    FOREIGN KEY (`Solicitantes_idSolicitantes`)
    REFERENCES `jp2`.`Solicitantes` (`idSolicitantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apoyo_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `jp2`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jp2`.`Beneficiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jp2`.`Beneficiarios` (
  `idBeneficiarios` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NombreConyugue` VARCHAR(40) NOT NULL COMMENT '',
  `ApellidoPaCon` VARCHAR(30) NOT NULL COMMENT '',
  `ApellidoMaCon` VARCHAR(30) NOT NULL COMMENT '',
  `NombrePadre` VARCHAR(40) NOT NULL COMMENT '',
  `ApellidoPaPa` VARCHAR(30) NOT NULL COMMENT '',
  `ApellidoMaPa` VARCHAR(30) NOT NULL COMMENT '',
  `NombreMadre` VARCHAR(40) NOT NULL COMMENT '',
  `ApellidoPaMa` VARCHAR(30) NOT NULL COMMENT '',
  `ApellidoMaMa` VARCHAR(30) NOT NULL COMMENT '',
  `NombreSuegro` VARCHAR(40) NOT NULL COMMENT '',
  `ApellidoPaSu` VARCHAR(30) NOT NULL COMMENT '',
  `ApellidoMaSu` VARCHAR(30) NOT NULL COMMENT '',
  `NombreSuegra` VARCHAR(40) NOT NULL COMMENT '',
  `ApellidoPaSuegra` VARCHAR(30) NOT NULL COMMENT '',
  `ApellidoMaSuegra` VARCHAR(30) NOT NULL COMMENT '',
  `NombreHijo1` VARCHAR(40) NOT NULL COMMENT '',
  `ApellidoPaH1` VARCHAR(30) NOT NULL COMMENT '',
  `ApellidoMaH1` VARCHAR(30) NOT NULL COMMENT '',
  `NombreHijo2` VARCHAR(40) NOT NULL COMMENT '',
  `ApellidoPaH2` VARCHAR(30) NOT NULL COMMENT '',
  `ApellidoMaH2` VARCHAR(30) NOT NULL COMMENT '',
  `NombreHijo3` VARCHAR(40) NOT NULL COMMENT '',
  `ApellidoPaH3` VARCHAR(30) NOT NULL COMMENT '',
  `ApellidoMaH3` VARCHAR(30) NOT NULL COMMENT '',
  `Apoyo_idApoyo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idBeneficiarios`, `Apoyo_idApoyo`)  COMMENT '',
  INDEX `fk_Beneficiarios_Apoyo1_idx` (`Apoyo_idApoyo` ASC)  COMMENT '',
  CONSTRAINT `fk_Beneficiarios_Apoyo1`
    FOREIGN KEY (`Apoyo_idApoyo`)
    REFERENCES `jp2`.`Apoyo` (`idApoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jp2`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jp2`.`Pagos` (
  `idPagos` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NoRecibo` VARCHAR(20) NULL COMMENT '',
  `Cantidad` INT NULL COMMENT '',
  `Fecha` DATE NOT NULL COMMENT '',
  `OrdenServicio_Folio` INT NOT NULL COMMENT '',
  `OrdenServicio_Sucursal_idSucursal` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPagos`)  COMMENT '',
  INDEX `fk_Pagos_OrdenServicio1_idx` (`OrdenServicio_Folio` ASC, `OrdenServicio_Sucursal_idSucursal` ASC)  COMMENT '',
  CONSTRAINT `fk_Pagos_OrdenServicio1`
    FOREIGN KEY (`OrdenServicio_Folio` , `OrdenServicio_Sucursal_idSucursal`)
    REFERENCES `jp2`.`Orden` (`Folio` , `Sucursal_idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jp2`.`OrdenBeneficiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jp2`.`OrdenBeneficiarios` (
  `OrdenServicio_Folio` INT NOT NULL COMMENT '',
  `OrdenServicio_Sucursal_idSucursal` INT NOT NULL COMMENT '',
  `Beneficiarios_idBeneficiarios` INT NOT NULL COMMENT '',
  PRIMARY KEY (`OrdenServicio_Folio`, `OrdenServicio_Sucursal_idSucursal`, `Beneficiarios_idBeneficiarios`)  COMMENT '',
  INDEX `fk_OrdenServicio_has_Beneficiarios_Beneficiarios1_idx` (`Beneficiarios_idBeneficiarios` ASC)  COMMENT '',
  INDEX `fk_OrdenServicio_has_Beneficiarios_OrdenServicio1_idx` (`OrdenServicio_Folio` ASC, `OrdenServicio_Sucursal_idSucursal` ASC)  COMMENT '',
  CONSTRAINT `fk_OrdenServicio_has_Beneficiarios_OrdenServicio1`
    FOREIGN KEY (`OrdenServicio_Folio` , `OrdenServicio_Sucursal_idSucursal`)
    REFERENCES `jp2`.`Orden` (`Folio` , `Sucursal_idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenServicio_has_Beneficiarios_Beneficiarios1`
    FOREIGN KEY (`Beneficiarios_idBeneficiarios`)
    REFERENCES `jp2`.`Beneficiarios` (`idBeneficiarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
